# This file contains values from Cookiecutter

default_context:
  project_name: "PYGuides"
  project_description: "Usefull guides to deal with Python3 "
  github_user: "serykhelena"
  project_repository: "https://github.com/serykhelena/PYGuides"
  minimal_python_version: "3.8"
  email: "serykhelena@example.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
